name: nanodart
description: Tools for the NANO and BANANO cryptocurrencies including key generation, signing, encryption, and more.
version: 2.0.0
homepage: https://github.com/appditto/nanodart
author: Appditto LLC <hello@appditto.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pointycastle: ^3.1.3
  hex: ^0.2.0
  convert: ^3.0.1
  fixnum_nanodart: ^1.0.0
  bip39: ^1.0.6

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10